# -*- coding: utf-8 -*-
# ============================================================================
# Generated by the protocol buffer compiler. DO NOT EDIT!
# source: coordinator.proto
# ============================================================================
"""Generated protocol buffer code for coordinator.proto.

This file provides the message classes for the Predictive Adaptive Request
Allocation Framework's gRPC interface. It defines:

  - RequestClass enum (UNKNOWN, LIGHT, MEDIUM, HEAVY)
  - RouteRequestMsg / RouteRequestResponse
  - CompletionMsg / CompletionResponse
  - NodeIdMsg / NodeMetricsResponse
  - HealthCheckRequest / HealthCheckResponse

Note: In a real project, this file is auto-generated by running:
    python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. coordinator.proto

This manual version is provided so that downstream modules can import and
develop against the interface immediately, before grpcio-tools is installed.
"""

from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import symbol_database as _symbol_database

_sym_db = _symbol_database.Default()

# Descriptor placeholders — full binary descriptors are generated by protoc.
# This file uses a simplified runtime-compatible structure.

DESCRIPTOR = _descriptor.FileDescriptor(
    name='coordinator.proto',
    package='paf',
    syntax='proto3',
    serialized_options=None,
    serialized_pb=b''  # Placeholder — replace with actual protoc output
)


# ============================================================================
# Enum: RequestClass
# ============================================================================

class RequestClass:
    """Request classification label enum."""
    REQUEST_CLASS_UNKNOWN = 0
    REQUEST_CLASS_LIGHT = 1
    REQUEST_CLASS_MEDIUM = 2
    REQUEST_CLASS_HEAVY = 3

    _VALUE_TO_NAME = {
        0: 'REQUEST_CLASS_UNKNOWN',
        1: 'REQUEST_CLASS_LIGHT',
        2: 'REQUEST_CLASS_MEDIUM',
        3: 'REQUEST_CLASS_HEAVY',
    }

    _NAME_TO_VALUE = {v: k for k, v in _VALUE_TO_NAME.items()}

    @classmethod
    def name(cls, value: int) -> str:
        return cls._VALUE_TO_NAME.get(value, 'REQUEST_CLASS_UNKNOWN')

    @classmethod
    def value(cls, name: str) -> int:
        return cls._NAME_TO_VALUE.get(name, 0)


# ============================================================================
# Message Classes (Simplified Runtime Versions)
# ============================================================================
# These classes mirror the proto message structure and can be used for
# development and testing. Replace with actual protoc-generated classes
# when grpcio-tools is available.
# ============================================================================

class RouteRequestMsg:
    """Dispatched request from coordinator to a node."""
    def __init__(self, **kwargs):
        self.request_id: str = kwargs.get('request_id', '')
        self.request_class: int = kwargs.get('request_class', RequestClass.REQUEST_CLASS_UNKNOWN)
        self.confidence: float = kwargs.get('confidence', 0.0)
        self.endpoint: str = kwargs.get('endpoint', '')
        self.method: str = kwargs.get('method', '')
        self.payload_bytes: int = kwargs.get('payload_bytes', 0)
        self.source_id: str = kwargs.get('source_id', '')
        self.arrival_timestamp_ms: int = kwargs.get('arrival_timestamp_ms', 0)
        self.dispatch_timestamp_ms: int = kwargs.get('dispatch_timestamp_ms', 0)
        self.routing_hops: int = kwargs.get('routing_hops', 1)
        self.assigned_by: str = kwargs.get('assigned_by', 'allocation_engine')
        self.feature_vector: list = kwargs.get('feature_vector', [])
        self.experiment_id: str = kwargs.get('experiment_id', '')


class RouteRequestResponse:
    """Response from node after accepting/rejecting a request."""
    def __init__(self, **kwargs):
        self.accepted: bool = kwargs.get('accepted', True)
        self.node_id: str = kwargs.get('node_id', '')
        self.current_queue_depth: int = kwargs.get('current_queue_depth', 0)
        self.rejection_reason: str = kwargs.get('rejection_reason', '')


class CompletionMsg:
    """Node reports execution completion back to coordinator."""
    def __init__(self, **kwargs):
        self.request_id: str = kwargs.get('request_id', '')
        self.node_id: str = kwargs.get('node_id', '')
        self.request_class: int = kwargs.get('request_class', RequestClass.REQUEST_CLASS_UNKNOWN)
        self.execution_time_ms: float = kwargs.get('execution_time_ms', 0.0)
        self.queue_wait_time_ms: float = kwargs.get('queue_wait_time_ms', 0.0)
        self.total_time_ms: float = kwargs.get('total_time_ms', 0.0)
        self.completion_timestamp_ms: int = kwargs.get('completion_timestamp_ms', 0)
        self.cpu_pct: float = kwargs.get('cpu_pct', 0.0)
        self.queue_depth: int = kwargs.get('queue_depth', 0)
        self.success: bool = kwargs.get('success', True)
        self.error_message: str = kwargs.get('error_message', '')
        self.experiment_id: str = kwargs.get('experiment_id', '')


class CompletionResponse:
    """Coordinator acknowledgement of completion report."""
    def __init__(self, **kwargs):
        self.acknowledged: bool = kwargs.get('acknowledged', True)


class NodeIdMsg:
    """Coordinator requests metrics from a specific node."""
    def __init__(self, **kwargs):
        self.node_id: str = kwargs.get('node_id', '')


class NodeMetricsResponse:
    """Node's current live metrics."""
    def __init__(self, **kwargs):
        self.node_id: str = kwargs.get('node_id', '')
        self.cpu_pct: float = kwargs.get('cpu_pct', 0.0)
        self.memory_pct: float = kwargs.get('memory_pct', 0.0)
        self.queue_depth_light: int = kwargs.get('queue_depth_light', 0)
        self.queue_depth_medium: int = kwargs.get('queue_depth_medium', 0)
        self.queue_depth_heavy: int = kwargs.get('queue_depth_heavy', 0)
        self.queue_depth_total: int = kwargs.get('queue_depth_total', 0)
        self.latency_ema_ms: float = kwargs.get('latency_ema_ms', 0.0)
        self.throughput_rps: float = kwargs.get('throughput_rps', 0.0)
        self.capacity_score: int = kwargs.get('capacity_score', 100)
        self.vnode_count: int = kwargs.get('vnode_count', 150)
        self.total_requests_processed: int = kwargs.get('total_requests_processed', 0)
        self.total_requests_rejected: int = kwargs.get('total_requests_rejected', 0)
        self.timestamp_ms: int = kwargs.get('timestamp_ms', 0)
        self.is_healthy: bool = kwargs.get('is_healthy', True)
        self.uptime_sec: int = kwargs.get('uptime_sec', 0)


class HealthCheckRequest:
    """Health check ping message."""
    def __init__(self, **kwargs):
        self.sender_id: str = kwargs.get('sender_id', '')


class HealthCheckResponse:
    """Health check response from node."""
    def __init__(self, **kwargs):
        self.node_id: str = kwargs.get('node_id', '')
        self.healthy: bool = kwargs.get('healthy', True)
        self.uptime_sec: int = kwargs.get('uptime_sec', 0)
        self.timestamp_ms: int = kwargs.get('timestamp_ms', 0)
